# Generated by Django 5.0.8 on 2024-08-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="recipeingredient",
            order_with_respect_to="step",
        ),
        migrations.AlterOrderWithRespectTo(
            name="recipestep",
            order_with_respect_to="recipe",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="sequence",
        ),
        migrations.RemoveField(
            model_name="recipestep",
            name="sequence",
        ),
    ]
